# Generated by Django 4.2.4 on 2023-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('product', 'subsidiary')},
        ),
    ]
