# Generated by Django 4.2.4 on 2023-09-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('E', 'CAJA DE EFECTIVO'), ('B', 'CUENTA BANCARIA')], max_length=1, verbose_name='Tipo')),
                ('initial', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('old_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad Anterior')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('V', 'VENTA'), ('C', 'COMPRA'), ('M', 'EMPEÑO'), ('E', 'ENTRADA'), ('S', 'SALIDA')], default='V', max_length=1, verbose_name='TIPO')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='CORRELATIVO')),
                ('status', models.CharField(choices=[('R', 'REALIZADO'), ('A', 'ANULADO')], default='R', max_length=1, verbose_name='ESTADO')),
                ('init', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('current', models.DateField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('R', 'Realizado'), ('A', 'Anulado')], default='R', max_length=1, verbose_name='Estado')),
                ('type', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('A', 'Apertura'), ('C', 'Cierre')], max_length=1, verbose_name='Tipo')),
                ('payment', models.CharField(choices=[('E', 'Efectivo'), ('D', 'Deposito'), ('C', 'Credito')], max_length=1, verbose_name='Pago')),
                ('code_operation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo de operacion')),
                ('description', models.CharField(default='-', max_length=250, verbose_name='Descripcion de la operacion')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.account', verbose_name='E/B')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['id'],
            },
        ),
    ]
