# Generated by Django 4.2.4 on 2023-09-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
