# Generated by Django 4.2.4 on 2023-09-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETADO'), ('P', 'PENDIENTE'), ('A', 'ANULADO')], default='R', max_length=1, verbose_name='ESTADO'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('V', 'VENTA'), ('C', 'COMPRA'), ('M', 'EMPEÑO'), ('R', 'ENTREGA'), ('E', 'ENTRADA'), ('S', 'SALIDA')], default='V', max_length=1, verbose_name='TIPO'),
        ),
    ]
