# Generated by Django 4.2.4 on 2023-09-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_order_status_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'COMPLETADO'), ('P', 'PENDIENTE'), ('A', 'ANULADO')], default='P', max_length=1, verbose_name='ESTADO'),
        ),
    ]
