# Generated by Django 4.2.4 on 2023-09-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='relative',
            field=models.IntegerField(default=0, verbose_name='ORDER RELACIONAL'),
        ),
    ]
