# Generated by Django 4.2.4 on 2023-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero'),
        ),
    ]
