# Generated by Django 4.2.4 on 2023-09-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0002_payments_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subsidiary', verbose_name='Filial'),
        ),
    ]
